global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'elektri-vorg'
    static_configs:
      - targets: ['rwymo8fzm2o2eoet81n3bb7x.176.112.158.15.sslip.io']
    metrics_path: '/metrics'
    scheme: 'http'